# pull official base image
FROM node:13.12.0-alpine as build-stage

# set working directory
WORKDIR /

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent

# Copies everything over to Docker environment
COPY . .

# Uses port which is used by the actual application
EXPOSE 3000

# Run application
CMD [ "npm", "start" ]
